sudo: required

language: c
cache:
   directories:
      - obj/document

services:
  - docker

env:
  - TEST_SUITE=gnat-community-2019
  - TEST_SUITE=gnat-community-2019-insane

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --depth=1

script:
  - if [ "$TEST_SUITE" = "gnat-community-2019" ]; then docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2019.spark /bin/sh -c "ulimit -s unlimited; apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make testbulk examples"; fi
  - if [ "$TEST_SUITE" = "gnat-community-2019-insane" ]; then docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2019.spark /bin/sh -c "ulimit -s unlimited; apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make testinsane"; fi
