sudo: required

language: c
cache:
   directories:
      - obj/document

services:
  - docker

env:
  - TEST_SUITE=gnat-community-2019
  - TEST_SUITE=gnat-community-2019-insane
  - TEST_SUITE=gnat-community-2019-prove
  - TEST_SUITE=gnat-community-2020
  - TEST_SUITE=gnat-community-2020-insane
  - TEST_SUITE=gnat-community-2020-prove

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --depth=1

script:
  - if [ "$TEST_SUITE" = "gnat-community-2019" ]; then docker run -v $PWD:/app -w /app componolit/ci:gnat-community-2019 /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make testbulk examples"; fi
  - if [ "$TEST_SUITE" = "gnat-community-2019-insane" ]; then docker run -v $PWD:/app -w /app componolit/ci:gnat-community-2019 /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make testinsane"; fi
  - if [ "$TEST_SUITE" = "gnat-community-2019-prove" ]; then travis_wait 50 docker run -v $PWD:/app -w /app componolit/ci:gnat-community-2019 /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make GNATPROVE_OPTS=--report=all prove"; fi
  - if [ "$TEST_SUITE" = "gnat-community-2020" ]; then docker run -v $PWD:/app -w /app componolit/ci:gnat-community-2020 /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make testbulk examples"; fi
  - if [ "$TEST_SUITE" = "gnat-community-2020-insane" ]; then docker run -v $PWD:/app -w /app componolit/ci:gnat-community-2020 /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make testinsane"; fi
  - if [ "$TEST_SUITE" = "gnat-community-2020-prove" ]; then travis_wait 50 docker run -v $PWD:/app -w /app componolit/ci:gnat-community-2020 /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates wget time xz-utils && make GNATPROVE_OPTS=--report=all prove"; fi

after_script:
   - cat $PWD/obj/gnatprove/gnatprove.out
   - cat $PWD/tests/prove/gnatprove/gnatprove.out
